### PR TITLE
Add more exchange sources

### PR DESCRIPTION
**Pull request by techcoderx**
A lot of them no longer exist so new ones have to be added.

### CODE REVIEW

**Review by Rishi556 — APPROVED** [review]

**Comment by Rishi556** [comment]
Thanks! Added to a newly created develop branch and once I see it as being stable for a week or so I'll bring it over to master!

**Comment by Rishi556** [comment]
I noticed binance give this error: 
```
Exchange Binance is down! Skipping... true
Invalid response code or server error: null;Status CodeL 403
```

Any idea what might cause this?

**Comment by mebonline** [comment]
I think it is because of Binance's Geo Location block?

Binance.com is not available for some countries.
Especially, users from USA cannot use binance.com and https://api.binance.com/ too.

My hive feed is ok with this script and binance api for now.

**Comment by Rishi556** [comment]
Ah, I didn't know they geo blocked users. I was running in the US. Makes sense, thanks. Everything else looks good though, will probably get it into master early next week.

**Pull request merged**
